데이터를 해석하는 관점이 다 다르다

### 빅블러 (big blur)

- 산업간 경계가 사라지는 현상

### D I K W

- Data Infomation Knowledge Wisdom


In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


## 넘파이

인덱싱은 정수의 튜플로 인덱싱함
3차원은 면, 행, 열 순으로 인덱스

다양한 차원의 데이터를 쉽게 생성

- np.linspace(0, 100, 20)
- np.zeros(shape) : 0으로 구성된 N차원 배열 생성
- np.ones(shape) : 1로 구성된 N차원 배열 생성
- np.empty(shape) : 초기화되지 않은 N차원 배열 생성
- np.full(shape) : 주어진 값으로 채워진 새로운 배열
- np.tril(shape) : 하삼각행렬(Lower triangular matrix)을 반환
- np.eye(shape) : 단위행렬 생성
- np.full_like(shape) : 주어진 어레이의 형태와 타입을 갖는, 주어진 값으로 채워진 새로운 배열
- np.linspace(shape) : 지정한 구간을 균일한 간격으로 나누는 숫자들을 반환
- np.random.random(shape) : [0, 1) 사이의 범위에서 균일한 분포를 갖는 난수를 주어진 형태로 반환
- Np,random.randint(shape) : 주어진 범위에서 임의의 정수를 반환


In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2 = np.array(arr)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr2.ndim

2

In [7]:
arr2.dtype

dtype('int64')

In [8]:
arr2.nbytes

48

In [18]:
arr3 = arr2.astype(np.int8)
arr3.dtype

dtype('int8')

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.linspace(0, 100, 7)

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

In [23]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
a.reshape((3, 10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [28]:
np.full((4,4), 9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

## 데이터 슬라이싱 view 이기 때문에 값을 변경하면 원본이 바뀐다.


In [29]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[4]

4

In [31]:
arr[3: 8] = 1
arr

array([0, 1, 2, 1, 1, 1, 1, 1, 8, 9])

In [32]:
arr

array([0, 1, 2, 1, 1, 1, 1, 1, 8, 9])

In [33]:
## 차원 배열
arr2d = np.array(([1,2,3], [4,5,6], [7,8,9]))
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2d.shape

(3, 3)

In [36]:
arr2d[0][1]

2

In [40]:
arr2d[0,1]

2

In [42]:
arr3d = np.random.randint(1, 10, size= (3, 2, 3)) # 2행 3열짜리가 3개
arr3d

array([[[2, 2, 4],
        [1, 8, 6]],

       [[7, 9, 5],
        [2, 8, 6]],

       [[9, 2, 4],
        [8, 6, 4]]])

In [44]:
arr3d.shape

(3, 2, 3)

In [46]:
arr3d[1]

array([[7, 9, 5],
       [2, 8, 6]])

In [47]:
arr3d[1, 0, 1]

9

In [48]:
arr3d[2][0][0] = 80
arr3d

array([[[ 2,  2,  4],
        [ 1,  8,  6]],

       [[ 7,  9,  5],
        [ 2,  8,  6]],

       [[80,  2,  4],
        [ 8,  6,  4]]])

In [50]:
arr3d[2,0,:] 

array([80,  2,  4])

In [55]:
arr3d[0, 1, 0:2] = 20
arr2 = arr3d

In [62]:
arr2 = arr3d[0,1,0:2]
arr2[:] *= 100
arr2

array([10000, 10000])

In [66]:
arr4 = arr3d[0,1,0:2]/100
arr4

array([100., 100.])

In [61]:
arr3d

array([[[  2,   2,   4],
        [100, 100,   6]],

       [[  7,   9,   5],
        [  2,   8,   6]],

       [[ 80,   2,   4],
        [  8,   6,   4]]])

In [56]:
arr2

array([[[ 2,  2,  4],
        [20, 20,  6]],

       [[ 7,  9,  5],
        [ 2,  8,  6]],

       [[80,  2,  4],
        [ 8,  6,  4]]])

In [76]:
arr1 = arr2.copy()
arr1 = arr2[:]
arr1

array([100000, 100000])

In [59]:
arr1[0,0,0] = 100
print(arr1)
arr2

[[[100   2   4]
  [ 20  20   6]]

 [[  7   9   5]
  [  2   8   6]]

 [[ 80   2   4]
  [  8   6   4]]]


array([[[ 2,  2,  4],
        [20, 20,  6]],

       [[ 7,  9,  5],
        [ 2,  8,  6]],

       [[80,  2,  4],
        [ 8,  6,  4]]])

In [71]:
arrslice = np.arange(1,10)
arrslice = arrslice.reshape(3,3)
arrslice

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arrslice[:2, 1:]

array([[2, 3],
       [5, 6]])

In [73]:
arrslice[2, :]

array([7, 8, 9])

In [74]:
arrslice[:, 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [75]:
arrslice[1, :2]

array([4, 5])

In [80]:
arrslice2 = arrslice[:]
arrslice2

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
arrslice2[0,:] = 10
arrslice

array([[10, 10, 10],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [79]:
arrslice2

array([[0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr_copy = arr.copy()  # 깊은 복사
arr_copy[0] = 999

print("원본 배열:", arr)         # [1 2 3 4 5]
print("복사된 배열:", arr_copy)  # [999   2   3   4   5]
print("메모리 주소 동일 여부:", arr_copy.base is arr)  # False

원본 배열: [1 2 3 4 5]
복사된 배열: [999   2   3   4   5]
메모리 주소 동일 여부: False


In [122]:
data = np.random.randn(7, 4) # 정규분포 랜덤값
data

array([[ 1.80630771,  0.77946582,  0.09043428, -0.02840631],
       [ 0.92858261,  0.45330463, -0.16992287,  0.92609568],
       [ 0.89256389,  0.7899684 ,  0.1713835 ,  0.84892695],
       [-0.4014131 ,  0.24387907,  1.72613194, -0.23916973],
       [-0.04064144, -0.46384033,  0.04748168,  0.69355285],
       [ 0.73443207, -0.93477862, -0.1944822 , -1.64142283],
       [ 0.98698753, -0.3125138 , -0.94167878, -1.6356425 ]])

In [123]:
names = np.array(['A', 'B', 'D', 'D', 'B', 'C', 'D'])
names == 'B'

array([False,  True, False, False,  True, False, False])

In [124]:
data[names == 'D'] #트루인 행만 가져온다.

array([[ 0.89256389,  0.7899684 ,  0.1713835 ,  0.84892695],
       [-0.4014131 ,  0.24387907,  1.72613194, -0.23916973],
       [ 0.98698753, -0.3125138 , -0.94167878, -1.6356425 ]])

In [125]:
mask = (names == 'D') | (names == 'A')
data2 = data[mask] 

In [126]:
# data[mask] = 0
# data[mask]

In [127]:
data2[:,:2] = 0

In [128]:
data

array([[ 1.80630771,  0.77946582,  0.09043428, -0.02840631],
       [ 0.92858261,  0.45330463, -0.16992287,  0.92609568],
       [ 0.89256389,  0.7899684 ,  0.1713835 ,  0.84892695],
       [-0.4014131 ,  0.24387907,  1.72613194, -0.23916973],
       [-0.04064144, -0.46384033,  0.04748168,  0.69355285],
       [ 0.73443207, -0.93477862, -0.1944822 , -1.64142283],
       [ 0.98698753, -0.3125138 , -0.94167878, -1.6356425 ]])

In [130]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [138]:
arr = np.arange(20).reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [139]:
#원하는 행 뽑아서 맘대로 정렬
arr[[4,2,1,3]]

array([[16, 17, 18, 19],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [140]:
arr[[-1,-2,-4]] #뒤에서 첫번째, 뒤에서 두번째, 뒤에서 4번째

array([[16, 17, 18, 19],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7]])

In [142]:
arr = np.arange(50).reshape(10,5)
print(arr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


array([ 5, 28, 36, 12])

In [143]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
np.dot(arr1, arr2)

array([[19, 22],
       [43, 50]])

In [146]:
arr1.sum()

10

In [147]:
arr2.prod()

1680

In [148]:
arr1.mean()

2.5

In [149]:
arr1.std()

1.118033988749895

In [150]:
arr1 +10

array([[11, 12],
       [13, 14]])

In [151]:
import numpy as np

A = np.array([[1,2,3], [4,5,6]])
B = np.array([[7,8,9], [10,11,12]])

In [152]:
A+ B

array([[ 8, 10, 12],
       [14, 16, 18]])

In [153]:
A*B

array([[ 7, 16, 27],
       [40, 55, 72]])

In [154]:
A/B

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [156]:
B.swapaxes(1,0)

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

In [158]:
np.dot(A, B.swapaxes(1,0))

array([[ 50,  68],
       [122, 167]])

In [159]:
A*100

array([[100, 200, 300],
       [400, 500, 600]])

In [160]:
B/100

array([[0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12]])

In [163]:
C = np.array([1,2,3])
C

array([1, 2, 3])

In [164]:
A+C #브로드캐스팅 열이 복사됨

array([[2, 4, 6],
       [5, 7, 9]])

In [166]:
D = np.array([[100], [200]])
A+D

array([[101, 102, 103],
       [204, 205, 206]])

In [167]:
D

array([[100],
       [200]])

In [168]:
D.T

array([[100, 200]])

In [169]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
A.sum(axis = 0) #모든 행의 값을 다 더해라 결과는 열의 개수만큼

array([5, 7, 9])

In [171]:
A.sum(axis = 1) #모든 열의 값을 다 더해라 결과는 행의 개수만큼

array([ 6, 15])

In [176]:
print(A)

[[1 2 3]
 [4 5 6]]


In [178]:
print(A.max())
print(A.min())

6
1


In [183]:
arr3d = np.arange(2*3*4).reshape(2,3,4)
arr3d # 2,3,4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [184]:
# 4,3,2
arr3d.transpose()

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [186]:
arr3d.T.T

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [189]:
arr3d.swapaxes(0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [190]:
a = [1, 2,3, 4, 9.2]
a

[1, 2, 3, 4, 9.2]

In [191]:
np.array(a)

array([1. , 2. , 3. , 4. , 9.2])

# Pandas


In [228]:
import numpy as np
data = np.loadtxt('chocolate_rating.csv', delimiter=',')
print("차원", data.ndim)
print("모양", data.shape)
print("원소수", data.size)

차원 2
모양 (1795, 4)
원소수 7180


In [235]:
import pandas as pd

df = pd.read_csv('chocolate_rating.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1794 entries, 0 to 1793
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   1       1794 non-null   int64  
 1   2016    1794 non-null   int64  
 2   0.63    1794 non-null   float64
 3   3.75    1794 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 56.2 KB


In [230]:
rating_mean = data[:, 3].mean()
rating_mean

3.185933147632312

In [231]:
high_level = data[data[:, 3] >= 4] # 맛의 점수라고 가정하고
high_id = high_level[:, 0].astype(np.int64)
print(high_id)

[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394 1426 1428 1433 1479 1488 1513 1516
 1529 1530 1531 1533 1536 1537 1544 1545 1664 1683 1686 1688 1694 1700
 1740 1757]


In [232]:
five_level = data[data[:, 3].astype(np.int64) == 5] # 5점인 초콜릿
five_id = five_level[:, 0].astype(np.int64)
print(five_id)

[79 87]


In [233]:
mask = data[:, 3].astype(np.int64) == 5

In [261]:
# 2015년도에 제일 우수한 초콜릿(제일 많이 판매량)
# 3번째 인덱스값을 판매량이라고 가정한다.
# 2015년 데이터 중 판매량이 3 이상인 초콜릿 필터링
mask = (data[:, 1] == 2015) & (data[:, 3] >= 3)

# 조건에 맞는 행 추출
best_choco = data[mask]

# 첫 번째 열(ID) 추출
ids = best_choco[:, 0]
ids

array([   3.,    4.,    5.,   24.,   25.,   70.,   71.,   72.,   73.,
         74.,   75.,  113.,  114.,  115.,  116.,  117.,  118.,  120.,
        121.,  145.,  146.,  151.,  152.,  195.,  255.,  262.,  263.,
        264.,  266.,  267.,  273.,  290.,  291.,  296.,  299.,  318.,
        319.,  320.,  348.,  349.,  350.,  359.,  360.,  361.,  383.,
        387.,  403.,  404.,  405.,  406.,  407.,  413.,  439.,  440.,
        446.,  479.,  480.,  484.,  512.,  513.,  514.,  515.,  520.,
        521.,  538.,  549.,  556.,  557.,  582.,  595.,  597.,  598.,
        599.,  600.,  601.,  611.,  620.,  621.,  665.,  666.,  667.,
        671.,  707.,  708.,  729.,  730.,  731.,  732.,  733.,  735.,
        750.,  786.,  787.,  788.,  802.,  804.,  805.,  806.,  807.,
        818.,  819.,  820.,  821.,  849.,  877.,  945.,  946.,  947.,
        948.,  949.,  950.,  962.,  963.,  964.,  965.,  966., 1022.,
       1023., 1037., 1038., 1039., 1041., 1042., 1044., 1045., 1050.,
       1051., 1052.,

In [255]:
data[(data[:, 1] == 2015) | (data[:, 3] >= 1)]

array([[1.000e+00, 2.016e+03, 6.300e-01, 3.750e+00],
       [2.000e+00, 2.015e+03, 7.000e-01, 2.750e+00],
       [3.000e+00, 2.015e+03, 7.000e-01, 3.000e+00],
       ...,
       [1.793e+03, 2.011e+03, 6.500e-01, 3.500e+00],
       [1.794e+03, 2.011e+03, 6.200e-01, 3.250e+00],
       [1.795e+03, 2.010e+03, 6.500e-01, 3.000e+00]])

In [250]:
data[:, 1] == 2015

array([False,  True,  True, ..., False, False, False])

In [251]:
data[:, 3] >= 1

array([ True,  True,  True, ...,  True,  True,  True])

In [254]:
print(data[:, 1].dtype)  # 확인: int 또는 str
print(data[:, 3].dtype)  # 확인: float 또는 str

float64
float64


In [259]:
(data[:, 1] == 2015) & (data[:, 3] >= 1)

array([False,  True,  True, ..., False, False, False])